server:
  port: ${PORT:8001}
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:hair}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:jzarate}
    password: ${POSTGRES_PASSWORD:2004}
  jpa:
    hibernate:
      ddl-auto: update

  jooq:
    sql-dialect: org.postgresql.Driver

eureka:
  client:
    enable: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true